Repository ansible/ansible-dev-tools, pull requests merged in 2023-12, with the labels that each got.

#58 Initial docs content for intro
  docs/getting_started.md
  docs/index.md
  docs/installation.md
  docs/introduction.md
  mkdocs.yml
Labels: documentation

#60 Contributor Guide entry in the docs
  .config/dictionary.txt
  docs/contributor_guide.md
  mkdocs.yml
Labels: documentation

#62 Add Content best practices in the user guide
  .config/dictionary.txt
  docs/content_best_practices.md
  docs/user_guide.md
  mkdocs.yml
Labels: documentation

#67 Enable ack workflow
  .github/workflows/ack.yml
Labels: skip-changelog

#66 Add ansible-development-environment
  .config/lock-requirements.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: enhancement

#73 Fix navigation inside user-guide
  .readthedocs.yml
  docs/contributor-guide.md
  docs/getting-started.md
  docs/introduction.md
  docs/user-guide/content-best-practices.md
  docs/user-guide/index.md
  docs/user_guide.md
  mkdocs.yml
  tox.ini
Labels: bug

#72 Docs update, include ade and combine intro to index
  README.md
  docs/index.md
  docs/introduction.md
  mkdocs.yml
Labels: documentation, skip-changelog

#65 User Guide: Testing
  docs/user-guide/index.md
  docs/user-guide/testing.md
  mkdocs.yml
Labels: documentation, enhancement

#76 Update dependencies
  .config/lock-requirements.txt
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#75 Fix documentation navigation
  docs/contributor-guide.md
  docs/getting-started.md
  docs/index.md
  docs/installation.md
  docs/user-guide/testing.md
  mkdocs.yml
  tox.ini
Labels: bug

#78 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#77 Add ability to switch to other sister projects
  mkdocs.yml
Labels: bug

#80 Add a `tox.ini` example in content-best-practices
  .config/dictionary.txt
  docs/user-guide/content-best-practices.md
Labels: documentation, skip-changelog

#79 Expand installation instructions
  .config/dictionary.txt
  docs/index.md
  docs/installation.md
Labels: documentation, skip-changelog

#85 Remove getting started document
  .vscode/settings.json
  docs/getting-started.md
  docs/index.md
  docs/installation.md
  mkdocs.yml
Labels: skip-changelog

#86 Add creator link to docs
  docs/index.md
Labels: documentation, skip-changelog

#87 Add ansible-github-actions docs
  .config/dictionary.txt
  docs/user-guide/ci-setup.md
  docs/user-guide/content-release.md
  docs/user-guide/images/ci.png
  docs/user-guide/images/release.png
Labels: enhancement
