Repository ansible/ansible-dev-tools, pull requests merged in 2023-11, with the labels that each got.

#32 Rename project to ansible-dev-tools
  .gitignore
  README.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
  src/ansible_dev_tools/__init__.py
  src/ansible_dev_tools/__main__.py
  src/ansible_dev_tools/arg_parser.py
  src/ansible_dev_tools/cli.py
  src/ansible_dev_tools/version_builder.py
  tests/integration/test_basic.py
Labels: enhancement

#33 Require python 3.10 or newer
  .github/workflows/release.yml
  .github/workflows/tox.yml
  pyproject.toml
Labels: enhancement

#52 README update
  README.md
Labels: bug

#51 Add ansible-creator
  .config/lock-requirements.txt
  .config/requirements.in
  .config/requirements.txt
  README.md
  src/ansible_dev_tools/version_builder.py
Labels: enhancement

#54 Allow running push pipeline manually
  .github/workflows/push.yml
Labels: skip-changelog

#57 Avoid subfolders inside dist/
  tox.ini
Labels: skip-changelog
