Repository ansible/ansible-dev-tools, pull requests merged in 2024-10, with the labels that each got.

#398 Reduce number of layers in main container image
  devspaces/context/setup.sh
  final/Containerfile
  final/context/setup.sh
  final/setup.sh
  tools/image.sh
  tox.ini
Labels: bug

#397 Address onigurumacffi installation during testing
  .config/dictionary.txt
  .github/workflows/tox.yml
  .readthedocs.yml
  bindep.txt
  tools/test-setup.sh
  tox.ini
Labels: bug

#394 Update README.md
  README.md
Labels: bug, documentation

#393 Refactor devspaces build image to produce smaller image
  .config/dictionary.txt
  .github/workflows/tox.yml
  .gitignore
  devspaces/Containerfile
  devspaces/context/setup.sh
  tests/integration/test_server_creator.py
  tools/devspaces.sh
  tox.ini
Labels: minor

#402 Use shellcheck to lint bash scripts
  .pre-commit-config.yaml
  .vscode/extensions.json
  devspaces/context/setup.sh
  final/docker-prune.sh
  tests/integration/test_container.py
  tools/image.sh
Labels: bug

#404 Correct execution environment example in docs
  .gitignore
  docs/container.md
  docs/examples/execution-environment.yml
  docs/examples/requirements.txt
  docs/examples/requirements.yml
  mkdocs.yml
  tools/image.sh
Labels: bug

#392 Use a setup.sh script for configuring ee final container
  final/Containerfile
  final/setup.sh
  final/setup2.sh
  tools/image.sh
  tox.ini
Labels: bug

#410 Modify pipeline to publish ansible-devspaces image
  .github/workflows/tox.yml
Labels: skip-changelog

#412 Remove build-test action and use tox
  .github/actions/build-release/action.yml
  .github/actions/build-test/action.yml
  .github/dependabot.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  cspell.config.yaml
  tools/ee.sh
  tools/image.sh
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog

#414 Ensure devspaces image include latest wheel
  .gitignore
  devspaces/context/requirements.txt
  devspaces/context/setup.sh
  tools/devspaces.sh
Labels: bug

#423 Avoid using django-stubs[compatible-mypy] extra
  .config/requirements-test.in
  .pre-commit-config.yaml
Labels: minor

#424 Fix publish action
  .github/workflows/tox.yml
Labels: skip-changelog

#425 Workaround for avoiding incompatible ansible-creator version
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#428 Avoid canceling jobs on push to main
  .github/workflows/tox.yml
Labels: skip-changelog

#429 Move push workflow into tox one to avoid duplicate runs on push
  .github/workflows/push.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#407 Document use of OpenShift Dev Spaces
  .vscode/extensions.json
  .vscode/settings.json
  devfile.yaml
  devspaces/README.md
  devspaces/devfile.yaml
  docs/contributor-guide.md
  docs/devspaces.md
  mkdocs.yml
Labels: bug

#431 Reduce number of layers in ee image
  cspell.config.yaml
  final/Containerfile
  final/setup.sh
  final/setup2.sh
  tools/ee.sh
  tox.ini
Labels: minor

#433 Allow publish of packages from jobs requiring it
  .github/workflows/tox.yml
Labels: skip-changelog

#434 More permissions for testing pipeline
  .github/workflows/tox.yml
Labels: skip-changelog

#435 More permissions for testing pipeline
  .github/workflows/tox.yml
Labels: skip-changelog

#432 Further optimize the image building to reduce layers
  final/Containerfile
  final/setup.sh
  final/setup2.sh
Labels: bug

#440 Ensure that the tar file creation logic is encapsulated
  src/ansible_dev_tools/resources/server/creator.py
Labels: skip-changelog

#441 Refactor server creator class to V1 and update all the references
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .pre-commit-config.yaml
  src/ansible_dev_tools/resources/server/creator_v1.py
  src/ansible_dev_tools/subcommands/server.py
  tests/integration/test_container.py
  tests/integration/test_server_creator_v1.py
Labels: enhancement

#443 Update pre-commit hooks
  .pre-commit-config.yaml
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_container.py
Labels: skip-changelog

#442 Add server v2 API to reflect the creator CLI changes
  src/ansible_dev_tools/resources/server/creator_v2.py
  src/ansible_dev_tools/resources/server/data/openapi.yaml
  src/ansible_dev_tools/subcommands/server.py
  tests/integration/test_server_creator_v2.py
Labels: enhancement

#449 Default to oldest supported python for linting
  .github/workflows/tox.yml
  .pre-commit-config.yaml
Labels: skip-changelog

#450 Improve test failure output
  .pre-commit-config.yaml
  pyproject.toml
  tests/conftest.py
  tests/integration/conftest.py
Labels: skip-changelog

#446 ee: change container storage to use vfs
  final/setup.sh
Labels: bug

#439 Add oc command inside the containers
  .gitignore
  devspaces/context/setup.sh
  final/context/setup.sh
  final/setup.sh
  tests/integration/test_container.py
  tools/devspaces.sh
  tools/ee.sh
  tools/setup-image.sh
Labels: bug

#453 Update timeout for ui testing
  tests/integration/conftest.py
Labels: skip-changelog

#455 Update timeout for ui testing (take 2)
  tests/integration/test_container.py
Labels: skip-changelog

#454 Allow push to update release notes
  .github/workflows/tox.yml
Labels: skip-changelog
