Repository ansible/ansible-dev-tools, pull requests merged in 2024-09, with the labels that each got.

#346 Docsite, README: Add communication information
  README.md
  docs/contributor-guide.md
  mkdocs.yml
Labels: documentation, skip-changelog

#366 Squash image layers to save disk space
  .github/actions/build-test/action.yml
  .gitignore
  tox.ini
Labels: minor

#368 Address container build warnings
  final/Containerfile
Labels: skip-changelog

#354 Change Getting started EE guide reference to point to the relevant location
  docs/container.md
Labels: bug

#369 Remove IRC link from docs
  docs/contributor-guide.md
Labels: bug

#370 Use pipx to install build dependencies on GHA runners
  .github/actions/build-test/action.yml
Labels: skip-changelog

#367 Add test for container-in-container functionality
  tests/conftest.py
  tests/integration/test_container.py
Labels: skip-changelog

#364 Change default container user to root
  .devcontainer/devcontainer.json
  .devcontainer/docker/devcontainer.json
  .devcontainer/podman/devcontainer.json
  docs/container.md
  final/Containerfile
  tests/conftest.py
  tests/integration/test_container.py
Labels: minor

#372 Removing --user=root param for container-in-container test
  tests/integration/test_container.py
Labels: skip-changelog

#373 Configure dependabot to update actions
  .github/dependabot.yml
Labels: skip-changelog

#377 Add test for ansible-builder
  .config/dictionary.txt
  .devcontainer/devcontainer.json
  .devcontainer/docker/devcontainer.json
  .devcontainer/podman/devcontainer.json
  tests/conftest.py
  tests/fixtures/integration/test_container/execution-environment.yml
  tests/integration/test_container.py
Labels: bug

#375 Avoid docker build summaries
  .github/actions/build-test/action.yml
Labels: skip-changelog

#384 Add docker pruning script for GHA usage
  .config/dictionary.txt
  .github/workflows/tox.yml
  final/docker-prune.sh
  pyproject.toml
Labels: skip-changelog

#383 Ensure ansible-compat is updated separately
  .github/dependabot.yml
Labels: skip-changelog

#371 Run image building in parallel with tox tests
  .github/workflows/tox.yml
Labels: skip-changelog

#386 Minor build fixes
  .config/pydoclint-baseline.txt
  .gitignore
  .pre-commit-config.yaml
  bindep.txt
  pyproject.toml
  tests/conftest.py
  tests/integration/test_container.py
  tox.ini
Labels: bug

#382 Add devspaces image building from ansible-workspace-env-reference-image
  .config/dictionary.txt
  .github/actions/build-release/action.yml
  .github/actions/build-test/action.yml
  .github/workflows/tox.yml
  devspaces/.gitignore
  devspaces/Containerfile
  devspaces/LICENSE
  devspaces/README.md
  devspaces/context/podman.py
  devspaces/context/requirements.txt
  devspaces/context/requirements.yml
  devspaces/context/setup.sh
  devspaces/devfile.yaml
  devspaces/playbooks/ansible-navigator.yml
  devspaces/playbooks/site.yaml
Labels: enhancement
