Repository ansible/ansible-dev-tools, pull requests merged in 2024-06, with the labels that each got.

#235 chore: Update tox.ini
  tox.ini
Labels: skip-changelog

#237 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#238 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#240 chore: Update .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: skip-changelog

#243 Manual dep update
  .config/constraints.txt
Labels: skip-changelog

#244 chore: Update .github/workflows/push.yml
  .github/workflows/push.yml
Labels: skip-changelog

#245 chore: Update .github/workflows/tox.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#246 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog

#247 Add known first party
  pyproject.toml
  src/ansible_dev_tools/resources/server/creator.py
  tests/conftest.py
Labels: skip-changelog

#253 Add some missing test requirements
  .config/requirements-test.in
Labels: skip-changelog

#254 Add lock extra to allow reproducible installation
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: enhancement

#256 Add reusable actions for building images
  .github/actions/build-test/action.yml
  .github/actions/merge-release/action.yml
Labels: skip-changelog

#257 chore: Update .vscode/settings.json
  .vscode/settings.json
Labels: skip-changelog

#258 Update pre-commit
  .pre-commit-config.yaml
Labels: skip-changelog

#260 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#255 Encapsulate community-ansible-dev-tools container building
  .config/dictionary.txt
  .devcontainer/devcontainer.json
  .devcontainer/docker/devcontainer.json
  .devcontainer/podman/devcontainer.json
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  ansible-navigator.yml
  bindep.txt
  docs/container.md
  execution-environment.yml
  final/Containerfile
  final/requirements.txt
  mkdocs.yml
  requirements.yml
  site.yml
  tests/ansible-navigator.yml
  tests/site.yml
  tests/test.sh
Labels: minor

#262 Correct test logs location
  ansible-navigator.yml
Labels: skip-changelog

#261 Add local image build environment for tox
  .github/actions/build-test/action.yml
  .gitignore
  final/Containerfile
  final/requirements.txt
  tox.ini
Labels: skip-changelog

#269 Disable update of referencing dependency
  .github/dependabot.yml
Labels: skip-changelog

#273 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog

#272 Sort, lowercase and remove duplicates in .config/dictionary.txt
  .config/dictionary.txt
Labels: skip-changelog

#282 Include release jobs with main tox one
  .github/actions/build-test/action.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#286 chore: Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: skip-changelog
