Repository ansible/ansible-dev-tools, pull requests merged in 2024-11, with the labels that each got.

#457 Avoid updating resolvelib in group updates
  .github/dependabot.yml
Labels: skip-changelog

#459 Make dependabot distinguish between minor and patch updates
  .github/dependabot.yml
Labels: skip-changelog

#460 More deps updates
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#462 Prevent canceling in progress jobs on release
  .github/workflows/tox.yml
  tests/integration/test_container.py
Labels: skip-changelog

#464 Use pytest logging instead of runtime warnings during testing
  pyproject.toml
  tests/conftest.py
Labels: skip-changelog

#466 Minor test improvements
  pyproject.toml
  tests/conftest.py
  tools/ee.sh
  tox.ini
Labels: skip-changelog

#465 Enable testing of devspaces container
  tools/devspaces.sh
  tools/ee.sh
Labels: skip-changelog

#468 Add support for py313
  pyproject.toml
Labels: enhancement

#471 Update expected number of coverage reports
  .github/workflows/tox.yml
Labels: bug

#474 Remove self type
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_dev_tools/cli.py
  src/ansible_dev_tools/resources/server/creator_v1.py
  src/ansible_dev_tools/resources/server/creator_v2.py
  src/ansible_dev_tools/subcommands/server.py
Labels: skip-changelog

#475 Remove self type
  src/ansible_dev_tools/resources/server/creator_v1.py
  src/ansible_dev_tools/resources/server/creator_v2.py
Labels: skip-changelog

#481 Update ansible-compat to v24.10
  .config/constraints.txt
  .config/requirements-lock.txt
Labels: minor
