Repository ansible/ansible-dev-tools, pull requests merged in 2024-07, with the labels that each got.

#296 Update base image to Fedora 40
  execution-environment.yml
  final/Containerfile
Labels: enhancement

#297 docs(fix): code blocks with titles
  docs/container.md
Labels: skip-changelog

#299 Link from docs to docs
  docs/index.md
Labels: skip-changelog

#298 Container testing framework
  .config/dictionary.txt
  tests/conftest.py
  tests/integration/test_container.py
Labels: enhancement

#309 Minor doc updates
  docs/container.md
  docs/user-guide/building-collection.md
Labels: skip-changelog

#311 Leverage pytest for testing container
  .github/actions/build-test/action.yml
  .pre-commit-config.yaml
  ansible-navigator.yml
  docs/contributor-guide.md
  tests/ansible-navigator.yml
  tests/conftest.py
  tests/fixtures/integration/test_container/site.yml
  tests/integration/test_container.py
  tests/site.yml
  tests/test.sh
  tox.ini
Labels: skip-changelog

#317 Improve handling of missing component
  src/ansible_dev_tools/version_builder.py
  tests/unit/__init__.py
  tests/unit/test_version_builder.py
Labels: bug

#318 Add argcomplete to image
  final/Containerfile
Labels: enhancement

#321 Add forum post
  .github/workflows/tox.yml
Labels: skip-changelog

#323 chore: Update .sonarcloud.properties
  .sonarcloud.properties
Labels: skip-changelog

#324 chore: Update .vscode/extensions.json
  .vscode/extensions.json
Labels: skip-changelog

#320 Additional images tests
  .config/constraints.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  final/Containerfile
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_container.py
  tox.ini
Labels: skip-changelog

#327 chore: Update pyproject.toml
  pyproject.toml
Labels: skip-changelog
