Repository ansible/ansible-dev-tools, pull requests merged in 2024-01, with the labels that each got.

#97 address GitHub action name change
  docs/user-guide/ci-setup.md
  docs/user-guide/content-release.md
Labels: bug

#105 Upgrade dependencies and rename ade
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  README.md
  docs/index.md
  docs/installation.md
  mkdocs.yml
  src/ansible_dev_tools/arg_parser.py
  src/ansible_dev_tools/version_builder.py
Labels: skip-changelog

#109 Auto update adt version output inside README
  README.md
  src/ansible_dev_tools/version_builder.py
  tools/update-readme.py
  tox.ini
Labels: bug

#112 Add collection building docs [part 1]
  docs/getting-started/building-collection.md
  docs/getting-started/index.md
  docs/index.md
  docs/installation.md
  docs/user-guide/building-collection.md
  mkdocs.yml
Labels: documentation, enhancement

#114 Remove duplicate guide
  docs/getting-started/building-collection.md
  docs/getting-started/index.md
  docs/index.md
  docs/installation.md
  docs/user-guide/index.md
  mkdocs.yml
Labels: bug

#116 Sort list of included tools
  docs/index.md
Labels: bug

#115 Add screen recordings to build a collection documentation
  .config/dictionary.txt
  docs/media/ansible-lint.mp4
  docs/media/ansible-navigator-run.mp4
  docs/media/compress.sh
  docs/media/create-collection.mp4
  docs/user-guide/building-collection.md
Labels: bug
