Repository ansible/ansible-dev-tools, pull requests merged in 2024-12, with the labels that each got.

#492 Adapt to newer dependabot config requirements
  .github/dependabot.yml
Labels: skip-changelog

#498 Use ubuntu-24.04 for testing
  .github/workflows/tox.yml
  .readthedocs.yml
  docs/user-guide/ci-setup.md
Labels: skip-changelog

#499 Ensure built image is fully qualified
  .config/requirements-test.in
  .gitignore
  pyproject.toml
  tests/conftest.py
  tests/integration/test_container.py
  tools/ee.sh
Labels: skip-changelog

#500 Replace pip-compile with uv pip compile
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  pyproject.toml
Labels: bug

#501 Switch reference python version to 3.11
  .config/constraints.txt
  .config/requirements-lock.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: minor

#484 Use fedora:41 as base image for the execution environment
  execution-environment.yml
  final/setup.sh
  tests/conftest.py
Labels: minor

#505 Fix container-in-container testing
  .pre-commit-config.yaml
  pyproject.toml
  tests/conftest.py
  tests/integration/test_container.py
Labels: skip-changelog

#506 Fix documentation pointing to OpenShift Dev Space
  docs/devspaces.md
Labels: bug

#507 Metadata API endpoint to display server information
  .github/workflows/tox.yml
  src/ansible_dev_tools/resources/server/data/openapi.yaml
  src/ansible_dev_tools/resources/server/server_info.py
  src/ansible_dev_tools/server_utils.py
  src/ansible_dev_tools/subcommands/server.py
  tests/integration/test_container.py
  tests/integration/test_server_info.py
  tools/devspaces.sh
  tools/ee.sh
  tox.ini
Labels: enhancement

#508 Adds devel testing pipeline
  .config/constraints.txt
  .config/requirements-test.in
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog
