Repository ansible/ansible-dev-tools, pull requests merged in 2025-05, with the labels that each got.

#570 Fix the formatting issue in the tag_name
  .github/workflows/tox.yml
Labels: bug

#571 Fix the sed command to update image sha
  .github/workflows/tox.yml
Labels: bug

#576 Add merge_group handler for tox workflow
  .github/workflows/tox.yml
Labels: patch

#579 Bump dependencies for May release
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
Labels: enhancement
