Repository ansible/ansible-dev-tools, pull requests merged in 2025-02, with the labels that each got.

#540 Send tar instead of gzipped tar file (required for RHDH plugins)
  src/ansible_dev_tools/resources/server/creator_v1.py
  src/ansible_dev_tools/resources/server/creator_v2.py
  src/ansible_dev_tools/resources/server/data/openapi.yaml
  tests/integration/test_server_creator_v1.py
  tests/integration/test_server_creator_v2.py
  tests/unit/test_server_utils.py
Labels: minor

#543 Fix devpsaces iptables version conflict
  devspaces/context/setup.sh
Labels: minor

#547 Fix condition for publishing ee
  .github/workflows/tox.yml
Labels: skip-changelog

#548 Add bug reporting template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: skip-changelog

#546 Update test isolation logic documentation
  docs/user-guide/test-isolation.md
Labels: bug

#550 Avoid errors with read only virtual envs
  .config/constraints.txt
  .config/pydoclint-baseline.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .pre-commit-config.yaml
Labels: bug

#552 Add RPM pinentry
  .config/dictionary.txt
  devspaces/context/setup.sh
Labels: bug
